version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/app.Dockerfile
        image: 'exsys-app' #change me
        container_name: 'exsys-app' #change me
        privileged: true
        volumes:
            - ./:/var/www:Z
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:Z
        networks:
            - exsys-network #change me
        # depends_on:
        #     - db
    
    server:       
        image: nginx:alpine
        container_name: 'exsys-nginx'
        restart: unless-stopped
        tty: true
        privileged: true
        volumes:
            - ./:/var/www:z 
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/:z #change this: ./.docker/nginx/conf.d/default.conf (fastcgi_pass default-laravel-app:9000;)
            - ./.docker/certs:/etc/nginx/certs
        ports:
            - "8000:80"
            # - "443:443"  
        networks:
            - exsys-network 

    # cache:
    #     image: redis:6
    #     container_name: default-laravel-cache
    #     restart: unless-stopped
    #     networks:
    #         - default-laravel-network

    # db:
    #     image: 'mysql:8.0.28'
    #     container_name: default-laravel-db #change me
    #     restart: unless-stopped
    #     ports:
    #         - "3306:3306"
    #     environment:
    #         MYSQL_DATABASE: default_laravel_db #change me
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_PASSWORD: root
    #         MYSQL_USER: chandra
    #         MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    #     volumes:
    #         - ./.docker/dbdata:/var/lib/mysql:Z
    #     networks:
    #         - default-laravel-network #change me

networks:
    exsys-network: #change me
        driver: bridge
